export const HANDEL_VIDEO_SELECT = "HANDEL_VIDEO_SELECT";
export const HANDEL_MODAL_CLOSE = "HANDEL_MODAL_CLOSE";
export const HANDEL_FEATURE_VIDEOS = "HANDEL_FEATURE_VIDEOS";
export const HANDEL_SET_VIDEOS = "HANDEL_SET_VIDEOS";
