export const HANDEL_VIDEO_SELECT = "HANDEL_VIDEO_SELECT";
export const HANDEL_MODAL_CLOSE = "HANDEL_MODAL_CLOSE";
export const OPEN_MODAL = "OPEN_MODAL";
export const HANDEL_SET_VIDEOS = "HANDEL_SET_VIDEOS";
